<?php
$this->htmlElement('body')->appendAttribute('class', 'datavis vis browse');
?>

<?php echo $this->pageTitle($this->translate('Visualizations'), 1, $this->translate('Data Visualization')); ?>

<?php if ($this->userIsAllowed('Datavis\Api\Adapter\DatavisVisAdapter', 'create')): ?>
<div id="page-actions">
    <div id="page-action-menu">
        <?php echo $this->hyperlink($this->translate('Add new visualization'), $this->url(null, ['action' => 'add-dataset-type'], true), ['class' => 'button']); ?>
    </div>
</div>
<?php endif; ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector([
    [
        'label' => $this->translate('Date created'),
        'value' => 'created',
    ],
    [
        'label' => $this->translate('Title'),
        'value' => 'title',
    ],
]); ?>
</div>

<?php if ($vises): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Visualization'); ?></th>
            <th><?php echo $this->translate('Dataset type'); ?></th>
            <th><?php echo $this->translate('Diagram type'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Created'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($vises as $vis): ?>
    <?php $owner = $vis->owner(); ?>
        <tr>
            <td>
                <?php echo $vis->title(); ?>
                <ul class="actions">
                    <?php if ($vis->userIsAllowed('update')): ?>
                    <?php if ($vis->datasetModified() && $vis->diagramType()): ?>
                    <li><?php echo $this->hyperlink('', $vis->diagramUrl(), ['class' => 'fa fa-chart-pie', 'title' => $this->translate('View diagram'), 'target' => '_blank']); ?></li>
                    <?php endif; ?>
                    <?php if ($vis->datasetModified()): ?>
                    <li><?php echo $this->hyperlink('', $vis->datasetUrl(['pretty_print' => true]), ['class' => 'fa fa-table', 'title' => $this->translate('View dataset'), 'target' => '_blank']); ?></li>
                    <?php endif; ?>
                    <li><?php echo $vis->link('', 'edit', ['class' => 'fa fa-pencil-alt', 'title' => $this->translate('Edit')]) ?></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php echo $this->translate($vis->getDatasetType()->getLabel()); ?></td>
            <td><?php echo $this->translate($vis->getDiagramType()->getLabel()); ?></td>
            <td><?php echo $owner ? $owner->link($owner->name()) : ''; ?></td>
            <td><?php echo $this->i18n()->dateFormat($vis->created()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>
<div class="no-resources">
    <?php if ($this->userIsAllowed('Datavis\Api\Adapter\DatavisVisAdapter', 'create')): ?>
    <p><?php echo sprintf(
        $this->translate('No visualizations found. %s'),
        $this->hyperlink($this->translate('Add a new visualization.'), $this->url(null, ['action' => 'add-dataset-type'], true))
    ); ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('No visualizations found.'); ?></p>
    <?php endif; ?>
</div>
<?php endif; ?>
